"""
FARS Prompts Module
Prompt模板
"""

from .templates import (
    IDEA_GENERATION_PROMPT,
    PAPER_ANALYSIS_PROMPT,
    EXPERIMENT_PLANNING_PROMPT,
    CODE_GENERATION_PROMPT,
    DEBUG_ASSISTANCE_PROMPT,
    STRATEGY_EVALUATION_PROMPT,
    PAPER_WRITING_PROMPT
)

__all__ = [
    "IDEA_GENERATION_PROMPT",
    "PAPER_ANALYSIS_PROMPT",
    "EXPERIMENT_PLANNING_PROMPT",
    "CODE_GENERATION_PROMPT",
    "DEBUG_ASSISTANCE_PROMPT",
    "STRATEGY_EVALUATION_PROMPT",
    "PAPER_WRITING_PROMPT"
]